name: KeePassium iOS Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install Dependencies
        run: |
          gem install cocoapods
          pod install

      - name: Build with Xcode
        run: |
          xcodebuild -workspace KeePassium.xcworkspace -scheme KeePassium -sdk iphoneos -configuration Release clean build
